  01_Exercice[m
  02_Exercice[m
  03_Exercice_get[m
  03_Exercice_les_formulaires[m
  04_Exercice_Les_formulaires[m
  05_Exercice_les_test_en_php[m
  06_Exercice_Q01[m
  06_Exercice_Q02[m
  1.7_Exercice_n_6_Les_formulaires[m
  2.1_Exercice_n1_Boucle_simple[m
* [32m2.2_Exercice_n2_Boucle_simple[m
  2.3_Exercice_n3_Boucle_simple[m
  2.4_Exercice_n4_deux_boucles_imbriquees[m
  3.1_Exercice_n1_fonction_simple_sans_parametre[m
  3.2_Exercice_n2_fonction_simple_avec_2_parametres_sans_retour[m
  3.4_Exercice_n4_utilisation_de_fonctions[m
  3.5_Exercice_n5_utilisation_de_fonctions[m
  3_Exercice_n3_fonction_simple_avec_3_parametre_et_un_retour[m
  4.1_Exercice_n1_ouvrir_un_fichier_texte[m
  4.2_Exercice_n2_ouvrir_un_fichier_texte_et_l_afficher[m
  4.3_Exercice_n3_ouvrir_un_fichier_texte[m
  4.4_Exercice_n4_creer_un_fichier_texte[m
  4.5_Exercice_n5_creer_un_fichier_texte[m
  4.6_Exercice_n6_supprimer_un_fichier[m
  4.7_Exercice_n7_les_dossier[m
  4.8_Exercice_n8_fichier_CSV[m
  Programme_affiche_nombre_entier_entre_41_et_100[m
  master[m
